name: 錯誤報告
description: 回報專案中的錯誤以幫助我們改進
title: "[BUG] "
labels: ["bug"]
assignees: []
body:
  - type: textarea
    id: description
    attributes:
      label: 錯誤描述
      description: 請詳細描述你遇到的問題。
      placeholder: 例如：按下登入按鈕後應用程式崩潰。
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: 重現步驟
      description: 提供重現錯誤的具體步驟。
      placeholder: |
        1. 前往登入頁面
        2. 輸入無效的電子郵件
        3. 點擊登入按鈕
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: 預期行為
      description: 描述你期望應該發生的情況。
      placeholder: 例如：應顯示「無效電子郵件」的錯誤訊息。
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: 實際行為
      description: 描述實際發生的情況。
      placeholder: 例如：應用程式崩潰並顯示空白畫面。
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: 嚴重程度
      description: 這個錯誤的影響程度是什麼？
      options:
        - 低（不影響使用）
        - 中（部分功能受限）
        - 高（無法使用主要功能）
      default: 1
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: 環境資訊
      description: 提供相關環境資訊（例如作業系統、瀏覽器版本等）。
      placeholder: 例如：Windows 10, Chrome 120.0.0
    validations:
      required: false
